name: Deployment Workflow
on: push

jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Install project dependencies
        run: npm i
      - name: Run tests
        run: npm test

  Run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Install project dependencies
        run: npm i
      - name: Run linter
        run: npm run lint

  Deploy:
    needs: [Run-linter, Run-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Install project dependencies
        run: npm i
      - name: Build the project
        run: npm run build
      - name: Deploy the project
        run: echo "Deploying ......."
